export const FETCH_SIMILAR_ARTISTS_REQUEST = 'FETCH_SIMILAR_ARTISTS_REQUEST';
export const FETCH_SIMILAR_ARTISTS_SUCCESS = 'FETCH_SIMILAR_ARTISTS_SUCCESS';
export const FETCH_SIMILAR_ARTISTS_FAILURE = 'FETCH_SIMILAR_ARTISTS_FAILURE';
